# Generated by Django 4.2.2 on 2023-08-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50, verbose_name='Kategori İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=50, verbose_name='Oyun Adı')),
                ('gameImage', models.ImageField(max_length=200, upload_to='game', verbose_name='Oyun Resmi')),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.categorygame', verbose_name='kategori ismi')),
            ],
            options={
                'verbose_name': 'Kart',
                'verbose_name_plural': 'Oyun Kartları',
            },
        ),
    ]
