# Generated by Django 4.2.2 on 2023-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecard',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
