# Generated by Django 4.2.2 on 2023-08-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryOffTopicName', models.CharField(max_length=50, verbose_name='Kategori İsmi')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Off-Topic',
                'verbose_name_plural': 'Konu Dışı',
            },
        ),
        migrations.AddField(
            model_name='gamecard',
            name='categoryOffTopicName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.categoryofftopic', verbose_name='konu ismi'),
        ),
    ]
