# Generated by Django 4.2.2 on 2023-08-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_categoryofftopic_gamecard_categoryofftopicname'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygame',
            name='categoryTopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.categoryofftopic', verbose_name='Konu Dışı'),
        ),
    ]
