# Generated by Django 4.2.2 on 2023-08-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_gamecard_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecard',
            old_name='gameImage',
            new_name='gameimage',
        ),
    ]
