# Generated by Django 4.2.2 on 2023-08-31 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_categorygame_categorytopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tip')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorygame',
            name='categoryTopic',
        ),
        migrations.RemoveField(
            model_name='gamecard',
            name='categoryOffTopicName',
        ),
        migrations.DeleteModel(
            name='CategoryOffTopic',
        ),
        migrations.AddField(
            model_name='gamecard',
            name='forumTyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.forumtyp', verbose_name='forum tipi'),
        ),
    ]
