# Generated by Django 4.2.2 on 2023-08-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_rename_gameimage_gamecard_gameimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecard',
            old_name='gameimage',
            new_name='gameImage',
        ),
    ]
