# Generated by Django 4.2.2 on 2023-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_forumtyp_remove_categorygame_categorytopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtyp',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
