# Generated by Django 4.2.2 on 2023-08-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
