# Generated by Django 4.2.2 on 2023-08-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygame',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Oyun Kategorileri'},
        ),
    ]
