# Generated by Django 4.2.2 on 2023-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_alter_categorygame_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygame',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
