# Generated by Django 4.2.2 on 2023-08-15 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Tarih - Saat')),
                ('subject_brand', models.CharField(max_length=100, null=True, verbose_name='Konu Başlığı')),
                ('game_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.gamecard', verbose_name='Konuya bağlı Kategori İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profil Resmi')),
                ('loginUser', models.BooleanField(blank=True, null=True, verbose_name='Girişli mi?')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası')),
                ('birthday', models.DateField(default=None, null=True, verbose_name='Doğum Tarihi')),
                ('comment', models.ManyToManyField(blank=True, to='appUser.comment', verbose_name='Kullanıcı Yorumları')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
