# Generated by Django 4.2.2 on 2023-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject_brand',
            field=models.CharField(max_length=100, null=True, verbose_name='Konu Başlığı'),
        ),
    ]
