# Generated by Django 4.2.2 on 2023-08-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_comment_subject_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='fname',
        ),
    ]
