# Generated by Django 4.2.2 on 2023-08-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_remove_comment_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fname',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim Soyisim'),
        ),
    ]
