# Generated by Django 4.2.2 on 2023-08-14 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUser', '0003_comment_game_cate_comment_subject_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Kulanıcı Adı')),
                ('image', models.ImageField(upload_to='profile', verbose_name='Profile Resmi')),
                ('loginP', models.BooleanField(verbose_name='Girişli mi?')),
                ('password', models.CharField(max_length=50, verbose_name='Kullanıcı Şiresi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('birthday', models.DateField(verbose_name='Dagum Tarihi')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('comment', models.ManyToManyField(to='appUser.comment', verbose_name='Kullanıcı Yorumları')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
