# Generated by Django 4.2.2 on 2023-08-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectBrand', models.CharField(max_length=50, verbose_name='Konu Başlığı')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appUser.subject', verbose_name='Konu Başlığı'),
        ),
    ]
