# Generated by Django 4.2.2 on 2023-08-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=None, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.ManyToManyField(blank=True, to='appUser.comment', verbose_name='Kullanıcı Yorumları'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profil Resmi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='loginUser',
            field=models.BooleanField(blank=True, null=True, verbose_name='Girişli mi?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
