# Generated by Django 4.2.2 on 2023-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='E-mail'),
        ),
    ]
