# Generated by Django 4.2.2 on 2023-08-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_subject_alter_comment_subject_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject_brand',
            field=models.CharField(max_length=100, null=True, verbose_name='Konu Başlığı'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
