# Generated by Django 4.2.2 on 2023-08-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_delete_comment'),
        ('appUser', '0005_remove_comment_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='game_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.gamecard', verbose_name='Konuya bağlı Kategori İsmi'),
        ),
    ]
