# Generated by Django 4.2.2 on 2023-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_profile_birthday_profile_comment_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=None, null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
