# Generated by Django 4.2.2 on 2023-08-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0006_subject_alter_comment_subject_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
