# Generated by Django 4.2.2 on 2023-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0007_remove_comment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profileimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile', verbose_name='Profil Resmi')),
            ],
        ),
    ]
