# Generated by Django 4.2.2 on 2023-08-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0009_comment_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_avatars', to='appUser.profileimage', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_avatar', to='appUser.profileimage', verbose_name='Profil Resmi'),
        ),
    ]
