# Generated by Django 4.2.2 on 2023-08-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
        ('appUser', '0010_alter_comment_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='game_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.gamecard', verbose_name='Konuya Bağlı Kategori İsmi'),
        ),
    ]
