# Generated by Django 4.2.2 on 2023-08-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0011_subject_game_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment_user',
            field=models.IntegerField(default=0, null=True, verbose_name='Kullanıcı Yorum Sayısı'),
        ),
        migrations.AddField(
            model_name='subject',
            name='comment_number',
            field=models.IntegerField(default=0, null=True, verbose_name='Başlık Yorum Sayısı'),
        ),
    ]
