# Generated by Django 4.2.2 on 2023-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0013_alter_profile_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loginUser',
            field=models.BooleanField(default=False, verbose_name='Girişli mi?'),
        ),
    ]
