# Generated by Django 4.2.2 on 2023-08-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0016_comment_typ_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='typ_comment',
        ),
    ]
