# Generated by Django 4.2.2 on 2023-08-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_forumtyp_remove_categorygame_categorytopic_and_more'),
        ('appUser', '0017_remove_comment_typ_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='typ_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.forumtyp', verbose_name='Konu tipi'),
        ),
    ]
