# Generated by Django 4.2.2 on 2023-09-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0018_comment_typ_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appUser.subject', verbose_name='Konu Başlığı'),
        ),
    ]
