# Generated by Django 4.2.2 on 2023-09-03 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUser', '0018_comment_typ_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='subject',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih - Saat'),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appUser.profileimage', verbose_name='Profil Resmi'),
        ),
    ]
