# Generated by Django 4.2.2 on 2023-09-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0019_alter_comment_subject_brand'),
        ('appUser', '0019_subject_author_subject_date_now_subject_image'),
    ]

    operations = [
    ]
